language: php

php:
  - '7.2'
  - '7.3'

install:
  - 'composer install'

script:
  - ./Packages/Libraries/bin/phpcs
  - ./Packages/Libraries/bin/phpstan analyze Classes
  - ./Packages/Libraries/bin/phpunit
